import type { Metadata } from "next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { inter } from "@/config/fonts";

import "./globals.css";
import { ProviderAuth } from "@/components";

export const metadata: Metadata = {
    title: {
        template: "%s -Teslo | Shop",
        default: "Home",
    },
    metadataBase: new URL("https://teslo-shop-nextjs-zeta.vercel.app"),
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ProviderAuth>{children}</ProviderAuth>
                <SpeedInsights />
            </body>
        </html>
    );
}
