import type { Metadata } from "next";
import { inter } from "@/config/fonts";

import "./globals.css";

export const metadata: Metadata = {
    title: {
        template: "%s -Teslo | Shop",
        default: "Home",
    },
    metadataBase: new URL("https://teslo-shop-nextjs-zeta.vercel.app"),
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>{children}</body>
        </html>
    );
}
